-- MySQL Script generated by MySQL Workbench
-- Thu May 25 22:15:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jxc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jxc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jxc` DEFAULT CHARACTER SET utf8 ;
USE `jxc` ;

-- -----------------------------------------------------
-- Table `jxc`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`supplier` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `sname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`product` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `cost` DOUBLE NOT NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`supplier_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`supplier_product` (
  `supplierId` INT NOT NULL,
  `productId` INT NOT NULL,
  PRIMARY KEY (`supplierId`, `productId`),
  INDEX `sproduct_fk_idx` (`productId` ASC),
  CONSTRAINT `ssupplier_fk`
    FOREIGN KEY (`supplierId`)
    REFERENCES `jxc`.`supplier` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sproduct_fk`
    FOREIGN KEY (`productId`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uname` VARCHAR(45) NOT NULL,
  `upwd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`customer` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `cname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`order` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `otime` DATETIME NOT NULL,
  `customerid` INT NOT NULL,
  `ostatus` INT NOT NULL,
  PRIMARY KEY (`oid`),
  INDEX `ocustomer_fk_idx` (`customerid` ASC),
  CONSTRAINT `ocustomer_fk`
    FOREIGN KEY (`customerid`)
    REFERENCES `jxc`.`customer` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`items` (
  `iid` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `iproductid` INT NOT NULL,
  `ipquantity` INT NOT NULL,
  PRIMARY KEY (`iid`),
  INDEX `iorder_fk_idx` (`orderid` ASC),
  INDEX `iproduct_fk_idx` (`iproductid` ASC),
  CONSTRAINT `iorder_fk`
    FOREIGN KEY (`orderid`)
    REFERENCES `jxc`.`order` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iproduct_fk`
    FOREIGN KEY (`iproductid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`purchaseorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`purchaseorder` (
  `poid` INT NOT NULL AUTO_INCREMENT,
  `ppid` INT NOT NULL,
  `psid` INT NOT NULL,
  `pquantity` INT NOT NULL,
  `ptime` DATETIME NOT NULL,
  `pstatus` INT NOT NULL,
  PRIMARY KEY (`poid`),
  INDEX `pproduct_fk_idx` (`ppid` ASC),
  INDEX `psupplier_fk_idx` (`psid` ASC),
  CONSTRAINT `pproduct_fk`
    FOREIGN KEY (`ppid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `psupplier_fk`
    FOREIGN KEY (`psid`)
    REFERENCES `jxc`.`supplier` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`purhuanorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`purhuanorder` (
  `phoid` INT NOT NULL AUTO_INCREMENT,
  `phpid` INT NOT NULL,
  `phsid` INT NOT NULL,
  `phhproductid` INT NOT NULL,
  `pquantity` INT NOT NULL,
  `phtime` DATETIME NOT NULL,
  `phstatus` INT NOT NULL,
  PRIMARY KEY (`phoid`),
  INDEX `pproduct_fk_idx` (`phpid` ASC),
  INDEX `psupplier_fk_idx` (`phsid` ASC),
  INDEX `phproduct_fk_idx` (`phhproductid` ASC),
  CONSTRAINT `pproduct_fk0`
    FOREIGN KEY (`phpid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `psupplier_fk0`
    FOREIGN KEY (`phsid`)
    REFERENCES `jxc`.`supplier` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `phproduct_fk`
    FOREIGN KEY (`phhproductid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`purtuiorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`purtuiorder` (
  `ptoid` INT NOT NULL AUTO_INCREMENT,
  `ptpid` INT NOT NULL,
  `ptsid` INT NOT NULL,
  `pquantity` INT NOT NULL,
  `pttime` DATETIME NOT NULL,
  `ptstatus` INT NOT NULL,
  PRIMARY KEY (`ptoid`),
  INDEX `pproduct_fk_idx` (`ptpid` ASC),
  INDEX `psupplier_fk_idx` (`ptsid` ASC),
  CONSTRAINT `pproduct_fk1`
    FOREIGN KEY (`ptpid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `psupplier_fk1`
    FOREIGN KEY (`ptsid`)
    REFERENCES `jxc`.`supplier` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`tuiorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`tuiorder` (
  `toid` INT NOT NULL AUTO_INCREMENT,
  `totime` DATETIME NOT NULL,
  `tcustomerid` INT NOT NULL,
  `tstatus` INT NOT NULL,
  PRIMARY KEY (`toid`),
  INDEX `ocustomer_fk_idx` (`tcustomerid` ASC),
  CONSTRAINT `ocustomer_fk0`
    FOREIGN KEY (`tcustomerid`)
    REFERENCES `jxc`.`customer` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`huanorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`huanorder` (
  `hoid` INT NOT NULL AUTO_INCREMENT,
  `hotime` DATETIME NOT NULL,
  `hcustomerid` INT NOT NULL,
  `hstatus` INT NOT NULL,
  PRIMARY KEY (`hoid`),
  INDEX `ocustomer_fk_idx` (`hcustomerid` ASC),
  CONSTRAINT `ocustomer_fk1`
    FOREIGN KEY (`hcustomerid`)
    REFERENCES `jxc`.`customer` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`huanitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`huanitems` (
  `hiid` INT NOT NULL AUTO_INCREMENT,
  `horderid` INT NOT NULL,
  `iproductid` INT NOT NULL,
  `ihproductid` INT NOT NULL,
  `hipquantity` INT NOT NULL,
  PRIMARY KEY (`hiid`),
  INDEX `iproduct_fk_idx` (`iproductid` ASC),
  INDEX `iorder_fk0_idx` (`horderid` ASC),
  INDEX `ihproduct_fk_idx` (`ihproductid` ASC),
  CONSTRAINT `iorder_fk0`
    FOREIGN KEY (`horderid`)
    REFERENCES `jxc`.`huanorder` (`hoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iproduct_fk0`
    FOREIGN KEY (`iproductid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ihproduct_fk`
    FOREIGN KEY (`ihproductid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jxc`.`tuiitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jxc`.`tuiitems` (
  `tiid` INT NOT NULL AUTO_INCREMENT,
  `torderid` INT NOT NULL,
  `iproductid` INT NOT NULL,
  `tupquantity` INT NOT NULL,
  PRIMARY KEY (`tiid`),
  INDEX `iproduct_fk_idx` (`iproductid` ASC),
  INDEX `iorder_fk1_idx` (`torderid` ASC),
  CONSTRAINT `iorder_fk1`
    FOREIGN KEY (`torderid`)
    REFERENCES `jxc`.`tuiorder` (`toid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iproduct_fk1`
    FOREIGN KEY (`iproductid`)
    REFERENCES `jxc`.`product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
